apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk-mariadb
  namespace: edutec
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-moodle
  labels:
    app: moodle
    namespace: edutec
spec:
  ports:
    - port: 3306
  selector:
    app: moodle
    tier: mariadb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-moodle
  labels:
    app: moodle
  namespace: edutec
spec:
  selector:
    matchLabels:
      app: moodle
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: mariadb
    spec:
      containers:
      - image: ado6595/mariadb:2.0
        name: mariadb
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MARIADB_USER
          value: bn_moodle
        - name: MARIADB_PASSWORD
          value: bitnami  
        - name: MARIADB_DATABASE
          value: bitnami_moodle
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
            - mountPath: "/bitnami/mariadb"
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: azure-disk-mariadb