apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mariadb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector: 
    matchLabels: 
      app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-moodle
  labels:
    app: moodle
spec:
  ports:
    - port: 3306
  selector:
    app: moodle
    tier: mariadb 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moodle
        tier: mariadb
    spec:
      containers:
      - image: bitnami/mariadb:10.2.36
        name: mariadb
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MARIADB_USER
          value: bn_moodle
        - name: MARIADB_PASSWORD
          value: bitnami  
        - name: MARIADB_DATABASE
          value: bitnami_moodle
        ports:
        - containerPort: 3306
          name: mariadb
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: "/bitnami/mariadb"
            name: vol-mariadb
      volumes:
        - name: vol-mariadb
          persistentVolumeClaim:
            claimName: mariadb-pvc